// angular/src/app/base/base.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';
import { navigateToUrl } from 'single-spa';

@Component({
  selector: 'app-base',
  imports: [RouterLink],
  templateUrl: './base.html',
})
export class Base {
  navigate(arg: string | Event) {
    if (typeof arg === 'string') {
      navigateToUrl(arg);
      return;
    }

    const target = arg.currentTarget;

    if (target instanceof HTMLAnchorElement) {
      arg.preventDefault();
      navigateToUrl(target.href);
      return;
    }
  }
}

// react/src/base/Base.tsx
import React from "react";
import { Link } from "react-router-dom";
import { navigateToUrl } from "single-spa";

export const Base: React.FC = () => {
  return (
    <div>
      <div>this is react</div>
      <Link to={"/react/config"}>view react config</Link>
      <br />
      <a href="/angular/config" onClick={navigateToUrl}>
        go to angular config
      </a>
    </div>
  );
};
